const themes = {
  spacing: {
    inputVertical: '10px',
    inputHorizontal: '10px',
    inputHorizontalBig: '20px',
    small: '0.3em',
    primary: '0.8em',
    septenary: '1.3em',
    tertiary: '2em',
    logo: '13em',
    headerNavVertical: '2em',
    headerNavVerticalTablet: '2em',
    headerNavHorizontal: '5em',
  },
  font: {
    family: {
      poppins: "'Poppins', sans-serif",
      quicksand: "'Quicksand', sans-serif",
    },
    weight: {
      light: 300,
      normal: 400,
      medium: 500,
      semiBold: 600,
      bold: 700,
      extraBold: 800,
      heavy: 900,
    },
    size: {
      hexadecimal: '0.375em',
      septenary: '0.6em',
      quinary: '0.72em',
      fourteenth: '0.875em',
      vistaco: '1.1em',
      tertiary: '1.2em',
      primary: '1em',
      oneAndHalf: '1.5em',
      secondary: '2em',
      quaternary: '2.6em',
    },
  },
  colors: {
    primary: '#000',
    secondary: '#fff',
    inputText: '#adadad',
    authBtn: '#F17119',
    link: '#c0392b',
    navbarBg: '#130f40',
    navbarText: '#c7ecee',
    homeBg: '#f5f6fa',
    tableBg: '#dcdde1',
    activationBg: '#bdc3c7',
    activationBox: '#ecf0f1',
    authBtnHover: '#e55b00',
    deleteBtn: '#FF0000',
    errorMsg: '#ff7675',
    errorBorderMsg: '#d63031',
  },
  media: {
    minTabletLandScape: '(min-width: 992px)',
    minLaptop: '(min-width: 1200px)',
    minPC: '(min-width: 1500px)',
    minPCFullHD: '(min-width: 1800px)',
    maxLowScreenMobile: '(max-width: 475px)',
    maxMobile: '(max-width: 768px)',
    maxTabletPortrait: '(max-width: 992px)',
    maxTabletLandScape: '(max-width: 1200px)',
    maxLaptop: '(max-width: 1500px)',
    maxPCFullHD: '(max-width: 1800px)',
    onlyTabletPortrait: '(min-width: 768px) and (max-width: 992px)',
    onlyTabletLandScape: '(min-width: 992px) and (max-width: 1200px)',
    onlyLaptop: '(min-width: 1200px) and (max-width: 1500px)',
    onlyPC: '(min-width: 1500px) and (max-width: 1800px)',
  },
  boxSizes: {
    authContainerWidth: '600px',
    authContainerHeight: '500px',
  },
};

export default themes;
