name: hackathon_CI_CD


on:
  - push
  - pull_request

env:
  DJANGO_SETTINGS_MODULE: user_management.settings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/user_management/requirements.txt
      - name: Check migration
        run: |
          python backend/user_management/manage.py makemigrations
          python backend/user_management/manage.py migrate
          python backend/user_management/manage.py check